image: eclipse-temurin:17

stages:
  - build
  - integrationtest

build-job:
  stage: build
  script:
    - echo "Hello Pipeline"
    - chmod +x ./mvnw
    - ./mvnw package

integrationtest-job:
  stage: integrationtest
  script:
    - echo "Hello Integration Tests"
